# Generated by Django 3.1 on 2019-12-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191218_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='備考 (詳細情報や何処で見つけた、何処に届けた届けたなど)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.IntegerField(choices=[(1, '落とした'), (2, '拾った')], default=1, verbose_name='落とした？or拾った？'),
        ),
    ]
